config/routes.rb
Rails.application.routes.draw do
  resources :styles

  resources :memberships do
    post 'confirm', on: :member
  end

  resources :beer_clubs

  resources :users do
    post 'toggle_blocked', on: :member
  end

  resources :beers

  get 'beerlist', to:'beers#list'
  get 'ngbeerlist', to:'beers#nglist'

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  get 'ngbrewerylist', to:'breweries#nglist'

  root 'breweries#index'

  get 'kaikki_bisset', to: 'beers#index'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :places, only:[:index]
  post 'places', to: 'places#search'
  get 'places/:city/:id', to: 'places#show', as: :place
  
  resources :ratings, only: [:index, :new, :create, :destroy]

  resource :session, only: [:new, :create, :delete]

end

app/models/beer_club.rb
class BeerClub < ActiveRecord::Base
	has_many :memberships
	has_many :users, through: :memberships
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :set_beer_club, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]

  # GET /beer_clubs
  # GET /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all
  end

  # GET /beer_clubs/1
  # GET /beer_clubs/1.json
  def show
    memberships = Membership.where user_id: session[:user_id], beer_club_id: @beer_club.id
    @already_member = memberships.empty?
    if @already_member
      @membership = Membership.new
      @membership.user_id = session[:user_id]
      @membership.beer_club_id = @beer_club.id
    else
      @membership = memberships.first
    end

    is_confirmed = Membership.where user_id: session[:user_id], beer_club_id: @beer_club.id, confirmed: true
    if not is_confirmed.empty?
      @unconfirmed = Membership.where beer_club_id: @beer_club.id, confirmed: nil
    end

    @confirmed_memberships = Membership.where confirmed: true, beer_club_id: @beer_club.id
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs
  # POST /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)

    respond_to do |format|
      if @beer_club.save

        membership = Membership.create(beer_club_id: @beer_club.id, user_id: session[:user_id], confirmed: true)

        format.html { redirect_to @beer_club, notice: 'Beer club was successfully created.' }
        format.json { render :show, status: :created, location: @beer_club }
      else
        format.html { render :new }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1
  # PATCH/PUT /beer_clubs/1.json
  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer_club }
      else
        format.html { render :edit }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1
  # DELETE /beer_clubs/1.json
  def destroy
    @beer_club.destroy
    respond_to do |format|
      format.html { redirect_to beer_clubs_url, notice: 'Beer club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer_club
      @beer_club = BeerClub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_club_params
      params.require(:beer_club).permit(:name, :founded, :city)
    end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_form.html.erb
<%= form_for(@beer_club) do |f| %>
  <% if @beer_club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
      <% @beer_club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :founded %><br>
    <%= f.number_field :founded %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-primary"%>
  </div>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing Beer Club</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer_club %> |
<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/index.html.erb
<h1>Listing Beer Clubs</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Founded</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beer_clubs.each do |beer_club| %>
      <tr>
        <td><%= beer_club.name %></td>
        <td><%= beer_club.founded %></td>
        <td><%= beer_club.city %></td>
        <td><%= link_to 'Show', beer_club %></td>
        <td><%= link_to 'Edit', edit_beer_club_path(beer_club) %></td>
        <td><%= link_to 'Destroy', beer_club, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beer club', new_beer_club_path, class:"btn btn-primary" %>

app/views/beer_clubs/new.html.erb
<h1>New Beer Club</h1>

<%= render 'form' %>

<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/show.html.erb
<h2><%= @beer_club.name %>, <%= @beer_club.city %></h2>
<p>Founded: <%= @beer_club.founded %></p>

<h3>Members:</h3>
<ul>
	<% @confirmed_memberships.each do |m| %>
		<% if m.confirmed %>
			<li><%= link_to m.user.username, user_path(m.user_id) %></li>
		<% end %>
	<% end %>
</ul>

<% if @already_member %>
	<%= form_for(@membership) do |f| %>
		<%= f.hidden_field :user_id %>
    <%= f.hidden_field :beer_club_id %>
    <%= f.submit value:"join the club", class:"btn btn-primary"%>
	<% end %>
<% else %>
	<%= form_for(@membership, method: "delete") do |f| %>
			<%= f.hidden_field :user_id %>
      <%= f.hidden_field :beer_club_id %>
      <%= f.submit value: "end the membership", class:"btn btn-primary btn-danger"%>
   <% end %>
<% end %>

<% if @unconfirmed %>
	<h3>Unconfirmed members:</h3>
	<ul>
		<% @unconfirmed.each do |m| %>
			<li><%= m.user.username %> <%= link_to "confirm membership", confirm_membership_path(m.id), method: :post, class: "btn btn-primary" %></li>
		<% end %>
	</ul>

<% end %>

<%= edit_and_destroy_buttons(@beer_club) %>