config/routes.rb
Rails.application.routes.draw do
  resources :styles

  resources :memberships do
    post 'confirm', on: :member
  end

  resources :beer_clubs

  resources :users do
    post 'toggle_blocked', on: :member
  end

  resources :beers

  get 'beerlist', to:'beers#list'
  get 'ngbeerlist', to:'beers#nglist'

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  get 'ngbrewerylist', to:'breweries#nglist'

  root 'breweries#index'

  get 'kaikki_bisset', to: 'beers#index'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :places, only:[:index]
  post 'places', to: 'places#search'
  get 'places/:city/:id', to: 'places#show', as: :place
  
  resources :ratings, only: [:index, :new, :create, :destroy]

  resource :session, only: [:new, :create, :delete]

end

app/models/user.rb
class User < ActiveRecord::Base
	include RatingAverage

	has_secure_password

	validates :username, uniqueness: true,
		length: { minimum: 3, 
				  maximum: 15 }
	validates :password, length: { minimum: 4}
	validates :password, format: { :with => /[A-Z]/, message: "at least one capital letter required" }
	validates :password, format: { :with => /[0-9]/, message: "at least one number required" }

	has_many :ratings
	has_many :raters, -> { uniq }, through: :ratings, source: :user
	has_many :memberships
	has_many :beer_clubs, through: :memberships

	def self.top(n)
	   sorted_by_rating_in_desc_order = User.all.sort_by{ |u| -(u.ratings.count||0) }
	   top = sorted_by_rating_in_desc_order[0..n-1]
	end

	def favorite_beer
		return nil if ratings.empty?
		ratings.order(score: :desc).limit(1).first.beer
	end

	def favorite_style
		return nil if ratings.empty?	
		id = style_sorted_ratings(ratings.includes(:beer).order("beers.style_id asc"))
		return Style.find id
	end

	def style_sorted_ratings(sorted_ratings)
		highest = 0;
		favorite = "";

		sorted_ratings.chunk { |r| 
			r.beer.style_id
		}.each { |style, ratings|
			avg = ratings.map { |r| r.score }.sum / ratings.count.to_f
			if avg > highest
				highest = avg
				favorite = style
			end
		}

		return favorite
	end

	def favorite_brewery
		return nil if ratings.empty?
		id = brewery_sorted_ratings((ratings.includes(:beer).order("beers.brewery_id desc")))
		Brewery.find id
	end

	def brewery_sorted_ratings(sorted_ratings)
		highest = 0;
		favorite = "";

		sorted_ratings.chunk { |r| 
			r.beer.brewery_id
		}.each { |brewery, ratings|
			avg = ratings.map { |r| r.score }.sum / ratings.count.to_f
			if avg > highest
				highest = avg
				favorite = brewery
			end
		}

		return favorite
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @status_text = @user.blocked ? 'unfreeze account' : 'freeze account'

    @memberships = Membership.where user_id: @user.id
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def toggle_blocked
    user = User.find(params[:id])
    user.update_attribute :blocked, (not user.blocked)

    new_status = user.blocked? ? "frozen" : "unfrozen"

    redirect_to :back, notice:"user status changed to #{new_status}"
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if user_params[:username].nil? and @user == current_user and @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    id = @user.id
    @user.destroy if current_user == @user
    session.destroy
    Rating.all.select{ |r| r.user.nil? }.each(&:delete)
    Membership.all.select{ |m| m.user_id == id }.each(&:delete)
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @user.new_record? %>
    <div class="field">
      <%= f.label :username %><br>
      <%= f.text_field :username %>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation  %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-primary"%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Change password of <%= @user.username %></h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td><% if user.blocked %> <span class="account-frozen">account frozen</span><% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class:"btn btn-primary" %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1><%= @user.username %><% if @user.blocked %> <span class="account-frozen">account frozen</span><% end %></h1>


<% if @user.ratings.empty? %>
	<p>This user has not rated any beers yet</p>
<% else %>
	<p>Has <%= pluralize(@user.ratings.count, 'rating') %>, average <%= round(@user.average_rating) %></p>
<% end %>
<p>Member of:</p>
<ul>
<% @memberships.each do |m| %>
	<% if m.confirmed %>
		<li><%= link_to m.beer_club.name, m.beer_club %></li>
	<% end %>
<% end %>
</ul>

<p>Applied membership of:</p>
<ul>
<% @memberships.each do |m| %>
	<% if not m.confirmed %>
		<li><%= link_to m.beer_club.name, m.beer_club %></li>
	<% end %>
<% end %>
</ul>

<% if !@user.favorite_beer.nil? %>
	<h2>Favorite beer: <%= @user.favorite_beer %></h2>
<% end %>
<% if !@user.favorite_style.nil? %>
	<h2>Favorite beer style: <%= @user.favorite_style %></h2>
<% end %>
<% if !@user.favorite_brewery.nil? %>
	<h2>Favorite brewery: <%= @user.favorite_brewery.name %></h2>
<% end %>

<h1>Ratings</h1>
<ul id="user-ratings">
<% @user.ratings.each do |r| %>
	<li>
		<%= r %> 
		<% if @user == current_user %>
			<%= link_to 'delete', r, method: :delete, id: 'delete-' + r.id.to_s %>
		<% end %>
	</li>
<% end %>
</ul>
<% if @user == current_user %>
	<%= link_to 'Edit', edit_user_path(@user), class:"btn btn-primary" %> |
	<%= link_to 'Delete', @user, class:"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>

<% if current_user and current_user.admin and @user != current_user %>
	<%= link_to @status_text, toggle_blocked_user_path(@user.id), method: :post, class: "btn btn-danger" %>
<% end %>

<%= link_to 'Back', users_path %>